name: DropHeads
version: '${project.version}'
main: me.matejpacan.dropheads.DropHeadsPlugin
api-version: '1.21'

author: Dasplet
description: Добавляет редкий шанс выпадения голов с мобов

commands:
    gethead:
        description: Получить голову моба
        usage: /<command> []
